pure_pursuit_controller_node:
  ros__parameters:
    max_throttle: 0.5
    min_throttle: -0.35
    odom_topic: /slam_pose
    control_topic: /control
    throttle_gain: 0.10
    ld_max: 2
    max_steer: 0.26
    max_vel: 0.2
    stop_distance: 0.5
    wheel_base: 0.324
    simulation: True


simulator_node:
  ros__parameters:
    control_topic: /control
    odom_topic: /slam_pose
    pub_rate: 30
    init_x: 2.0
    init_y: 0.5
    init_yaw: 0.0
    reset_service: /simulation/reset
    

routing_node:
  ros__parameters:
    odom_topic: /slam_pose
    lane_change_cost: 1.0
    goal_with_heading: False
    clicked_goal: True
    routing_path_topic: Routing/Path
    routing_pathL_topic: Routing/PathL
    routing_pathR_topic: Routing/PathR
    goal_topic: /goal_pose
    #map_file: maps/track.osm
  
visualization_node:
  ros__parameters:
    odom_topic: /slam_pose
    dyn_obs_topic: Obstacles/Dynamic

    


    